### ISSUE TITLE
GTDB taxonomic info

### ISSUE THREAD

**Issue by GaioTransposon** [iquasere/KEGGCharter#4] opened 2022-07-27 11:55 UTC
Hi Joao, 

As I use taxonomic info obtained through kraken (GTDB) instead of UPIMAPI, I did not expect all genera to be mapped, but it seems that practically none are mapped, not even the infamous Lactobacillus. These are the messages I get for practically all genera: 
```
[52/63] Getting information for taxon [Parabacteroides]
[0] maps inputted for org [pdi]
[0] KGMLs already obtained for org [pdi]
```
or
```
[40/63] Getting information for taxon [Anaerovibrio]
[Anaerovibrio] was not found in taxon to KEGG prefix conversion!
```
or
```
[48/63] Getting information for taxon [Lactobacillus]
[0] maps inputted for org [ljo]
[0] KGMLs already obtained for org [ljo]
```

What do you think could the problem be? 

My command: 
`keggcharter.py -f test.tsv -tcol "value" -koc "KO" -tc "Taxonomic lineage (GENUS)" -gcol "gcol" -o test_out -mm "Methane metabolism"`

Kind Regards
Dany

**Comment by iquasere** [comment] 2022-08-10 20:34
Could you share an input that reproduces this error?

**Comment by iquasere** [comment] 2022-12-14 11:17
Might look into this in the future. For now I will close the issue, since it is not a bug that needs fixing, but rather something that warrants to better look into, so KEGGCharter becomes compatible with GTDB.

**Closed as completed by iquasere** 2022-12-14 11:17 UTC
Labels: bug, enhancement
